### ISSUE TITLE
Vue JS Dev Tools - Not detecting VUE DOM

### ISSUE THREAD

**Issue by jonathantizard** [nklayman/vue-cli-plugin-electron-builder#268]
**Vue JS Dev Tools - installing but does not list elements** 
When running yarn electron:serve - the VUE JS dev tools are not registering any elements as VUE. However the tools are installed.

**To Reproduce**
1.  `electron:serve `
2. The App launches
3. Dev Tools installed but not working
<img width="989" alt="Screenshot 2019-05-08 at 11 13 14" src="https://user-images.githubusercontent.com/590023/57368309-c0739c00-7182-11e9-8b3a-11e9cdfe9f7a.png">

**Expected behavior**
1. After running the same command with no code changes the VUE devtools then work this is random and far between ( Same app and code but successful build here )
<img width="801" alt="Screenshot 2019-05-08 at 11 22 44" src="https://user-images.githubusercontent.com/590023/57368705-b30ae180-7183-11e9-9c3b-74a99ce26a9e.png">

**Package.json**
`{
  "name": "com.electron",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "test:e2e": "vue-cli-service test:e2e"
  },
  "main": "background.js",
  "dependencies": {
    "client-oauth2": "^4.2.3",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-router": "^3.0.6",
    "vuex": "^3.1.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.7.0",
    "@vue/cli-plugin-e2e-cypress": "^3.7.0",
    "@vue/cli-plugin-eslint": "^3.7.0",
    "@vue/cli-service": "^3.7.0",
    "@vue/eslint-config-prettier": "^4.0.1",
    "babel-cli": "^6.26.0",
    "babel-eslint": "^10.0.1",
    "electron": "^5.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-cli-plugin-electron-builder": "^1.3.1",
    "vue-template-compiler": "^2.5.21",
    "webpack-cli": "^3.3.1"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/prettier"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}`

**Additional context**
Not sure if the tools are trying to re install or there is a race condition before the browser loads? Or it might be silently failing?

**Comment by ant-i-c-s** [comment]
You could try putting `Vue.config.devtools = process.env.NODE_ENV === 'development';` in main.js before calling `new Vue` (https://github.com/vuejs/vue-devtools/issues/68). Otherwise, this might be due to using a non standard protocol (I looked in the extension's manifest.json and it has this line: `"permissions": [
    "http://*/*",
    "https://*/*",
    "file:///*",
    "contextMenus"
  ]`.

**Comment by jonathantizard** [comment]
Read the thread and tried a few things. Yea no luck for me.

**Comment by nklayman** [comment]
@ant-i-c-s In development, the `http` protocol is used, so there should be no issues there. I've had the same issue, usually a few reloads and maybe restarting electron fixes it. I have the same issue using [Quasar CLI](https://v1.quasar-framework.org/quasar-cli/developing-electron-apps/introduction), so i'm thinking this might be an issue with Vue Devtools, as the issue is not limited to this plugin's implementation of Electron. Maybe you could open an issue there as well, and we can work together to solve this problem as it seems quite common.

**Comment by jonathantizard** [comment]
Perfect - I have raised in vuejs / vue-devtools

**Comment by ciacka** [comment]
I encounter the same problem. I'm doing Vue.js development without electron in parallel and didn't faced with this issue.

**Comment by jonathantizard** [comment]
@nklayman Check this weirdness!

Running this will load electron but the promise on the URL load is a rejection? So the URL is rejecting on load but the app is running - add this to your main JS and see the error here:

`function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({ width: 800, height: 600, webPreferences: {
    nodeIntegration: true
  } })

  if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL).then((res) => {
    }).catch((e) => {
      if (!process.env.IS_TEST) win.webContents.openDevTools()
      console.log(e);
    })`

The error is this:

 Error: ERR_ABORTED (-3) loading 'http://localhost:8080/#/

Any thoughts?

**Comment by jonathantizard** [comment]
That URL actually doesnt work on my local machine because I am using node as well... so I can only see that URL working in electron.

**Comment by jonathantizard** [comment]
Final update https://github.com/SimulatedGREG/electron-vue - after bootstrapping that project the VUE JS DEV TOOLS work consistently. So something is causing it to not work correctly. So will have to use that project for now as developing on this is impossible for the mean time.

**Comment by nklayman** [comment]
After a little investigation, I realized Electron Vue does have the same issue. However, the issue is only preset on electron 3+. Electron Vue uses electron 2 by default, so the issue isn't present. If you use electron 3+ with that template, Vue devtools will fail the same way this plugin does. If you use electron 2 with this plugin, vue devtools works fine. With electron 3+ (on either tool), vue devtools works fine on initial load, but fails after reloading the page. I have noticed this with apollo devtools as well. This seems like an electron issue. We should probably open an issue there as well.

**Comment by baileyherbert** [comment]
I am using Electron 5 and ran into this issue as well. Nothing was being recognized by the extension, including the DOM and Vuex state.

I fixed it by closing the devtools window and reopening it (which can be done quickly by hitting the keybinding twice, e.g. Ctrl+Shift+I). It then recognized both the state and the DOM, and it continued working through hot reloads.

As an experiment, I tried delaying the initial `openDevTools()` call by several seconds, but it still did not work until I relaunched devtools.

**Comment by Ramin-Bateni** [comment]
Adding the 
```
Vue.config.devtools = process.env.NODE_ENV === 'development';
```
before `new Vue(...)` in `main.js` **solved my problem** :) but just when I run the project from the Terminal by 
```
npm run electron:serve
``` 
![image](https://user-images.githubusercontent.com/9051320/58958661-a4cad800-87b8-11e9-87f3-568de7d63c92.png)

---------------------------
**But**
If I run the project by **VS Code Debug** the problem is still there and Vue DevTools is empty again :(

![image](https://user-images.githubusercontent.com/9051320/58958351-f4f56a80-87b7-11e9-8f10-896417432d1b.png)


**Additional information:**

`tasks.json`:
```
{	
	"version": "2.0.0",
	"tasks": [
	  {
	    "label": "electron-debug",
	    "type": "process",
	    "command": "./node_modules/.bin/vue-cli-service",
	    "windows": {
		"command": "./node_modules/.bin/vue-cli-service.cmd"
	    },
	    "isBackground": true,
	    "args": ["electron:serve", "--debug"],
	    "problemMatcher": {
		"owner": "custom",
		"pattern": {
		  "regexp": ""
		},
		"background": {
		  "beginsPattern": "Starting development server\\.\\.\\.",
		  "endsPattern": "Not launching electron as debug argument was passed\\."
		}
	    }
	  }
	]
    }
```

`launch.json`:
```
{
	"version": "0.2.0",
	"configurations": [
	  {
	    "name": "Electron: Main",
	    "type": "node",
	    "request": "launch",
	    "protocol": "inspector",
	    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
	    "windows": {
				"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
	    },
	    "preLaunchTask": "electron-debug",
	    "args": ["--remote-debugging-port=9223", "./dist_electron"],
	    "outFiles": ["${workspaceFolder}/dist_electron/**/*.js"]
	  },
	  {
	    "name": "Electron: Renderer",
	    "type": "chrome",
	    "request": "attach",
	    "port": 9223,
	    "urlFilter": "http://localhost:*",
	    "timeout": 60000,
	    "webRoot": "${workspaceFolder}/src",
	    "sourceMapPathOverrides": {
				"webpack:///./src/*": "${webRoot}/*"
	    }
	  }
	],
	"compounds": [
	  {
	    "name": "Electron: All",
	    "configurations": ["Electron: Main", "Electron: Renderer"]
	  }
	]
    }
```

`vue.config.js`:
```
module.exports = {
	configureWebpack: {
		devtool: 'source-map'
	}
}
```

**Comment by gtamas** [comment]
Same here. Opening an closing devtools fixes it, but all tabs are empty when electron loads the window.

**Comment by dractw** [comment]
Same issue appeared in Electron 5, reopen devtools sometimes helps, sometimes not.

**Comment by rmaximoc** [comment]
Same here.
Sometimes I need to reopen devtools or reload it to back to work and sometimes works, sometimes doesn't

**Comment by char101** [comment]
A callback hell dance to automatically close and reopen vue devtools, to make it detect the Vue application in electron. The timeout would probably need to be adjusted to the speed of your computer/browser.

```javascript
const openVueDevTools = () =>
  mainWindow.webContents.devToolsWebContents.executeJavaScript(
    'DevToolsAPI.showPanel("chrome-extension://vue-js-devtoolsVue")',
  );
mainWindow.webContents.once('dom-ready', () => {
  mainWindow.webContents.openDevTools();
  mainWindow.webContents.once('devtools-opened', () => {
    setTimeout(() => {
      openVueDevTools();
      setTimeout(() => {
        mainWindow.webContents.closeDevTools();
        setTimeout(() => {
          mainWindow.webContents.openDevTools();
          mainWindow.webContents.once('devtools-opened', () => {
            setTimeout(openVueDevTools, 500);
          });
        }, 100);
      }, 500);
    }, 500);
  });
});
```

**Comment by gimzani** [comment]
I was having the same problem - and it was fixed adding the vue.config.js code:

```
module.exports = {
	configureWebpack: {
		devtool: 'source-map'
	}
}
```

I only got this to work in electron 5.  The comments say that it will not work in electron 6.  FYI.

Good luck!

**Comment by jonathantizard** [comment]
Nope - no luck for me. Still inconsistent.

**Comment by travis5491811** [comment]
The following has been consistently working for me _today_:
```JavaScript
// background.ts
...
  if (isDev) {
    setTimeout(() => {
      win.webContents.openDevTools();
    }, 3000);
  }
...
```

**Comment by jonathantizard** [comment]
Nope - sorry nothing for me. Still broken.

**Comment by dractw** [comment]
@travis5491811 No luck

**Comment by pacific202** [comment]
I'm struggling with this too.  None of the fixes above are working for me, and I need to see what's going on inside vuex.

**Comment by nklayman** [comment]
I think this issue has been solved, either from a vue devtools or electron update. Can someone confirm so this issue can be closed?

**Comment by jonathantizard** [comment]
OMG! YESSSSSSSSS. Its working for me now. Thank you for updating this issue. I can finally carry on with my project! Great news.

**Comment by Soolan** [comment]
I would appreciate some insight here as well.
What fixed the problem?

**Comment by nklayman** [comment]
Like I said in my previous comment, I believe an update in either vue devtools or electron fixed this issue. I haven't bothered to find out what specifically fixed it, you could test out different versions if you really want to know.
